# -*- coding: utf-8 -*-
"""DataProc

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rbaxePKizlLo475DvckUwLFoXESeZE3F
"""

import pandas as pd

class DataProcessor:
    def __init__(self, data):
        self.data = data

    def process(self):
        dfs = []
        for coluna in self.data.columns:
            df = pd.json_normalize(self.data[coluna][0]['events'])
            dfs.append(df)
        return pd.concat(dfs)