# -*- coding: utf-8 -*-
"""ModelTrainer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rbaxePKizlLo475DvckUwLFoXESeZE3F
"""

from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

class ModelTrainer:
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def train_model(self):
        # Stacking Classifier
        estimators = [('rf', RandomForestClassifier()),
                      ('gbc', GradientBoostingClassifier()),
                      ('nb', GaussianNB()),
                      ('knn', KNeighborsClassifier(n_neighbors=3))]
        stacking_classifier = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression(), cv=10, n_jobs=-1)
        stacking_classifier.fit(self.X, self.y)
        return stacking_classifier