# -*- coding: utf-8 -*-
"""DataFetcher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rbaxePKizlLo475DvckUwLFoXESeZE3F
"""

import requests

class DataFetcher:
    def __init__(self):
        self.base_url = 'https://api.sofascore.com/api/v1/'

    def fetch_team_events_total(self):
        url = self.base_url + 'unique-tournament/133/season/26681/team-events/total'
        return self.fetch_data(url)

    def fetch_quarterfinals(self):
        url = self.base_url + 'unique-tournament/133/season/26681/events/round/3/slug/quarterfinals'
        return self.fetch_data(url)

    def fetch_semifinals(self):
        url = self.base_url + 'unique-tournament/133/season/26681/events/round/2/slug/semifinals'
        return self.fetch_data(url)

    def fetch_match_for_3rd_place(self):
        url = self.base_url + 'unique-tournament/133/season/26681/events/round/50/slug/match-for-3rd-place'
        return self.fetch_data(url)

    def fetch_final(self):
        url = self.base_url + 'unique-tournament/133/season/26681/events/round/1/slug/final'
        return self.fetch_data(url)

    def fetch_data(self, url):
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()
        else:
            print("Falha ao obter dados de:", url)
            return None